GestorEventos.Cliente/Models/ErrorViewModel.cs
namespace GestorEventos.Cliente.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GestorEventos.Cliente/Models/Eventos.cs
using System.ComponentModel.DataAnnotations;

namespace GestorEventos.Cliente.Models
{
    public class Eventos
    {
        public int eventId { get; set; }
        
        [Required(ErrorMessage ="Este campo es requerido")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener maximo {1} caracteres")]
        public string eventName { get; set; }
        
        [Required(ErrorMessage = "Este campo es requerido")]
        [MaxLength(150, ErrorMessage = "El campo {0} debe tener maximo {1} caracteres")]
        public string eventDescription { get; set; }
        
        [Required(ErrorMessage = "Este campo es requerido")]
        public string startDate { get; set; }
        
        [Required(ErrorMessage = "Este campo es requerido")]
        public string endDate { get; set; }
        
        [Required(ErrorMessage = "Este campo es requerido")]
        public string eventStatus { get; set; }
    }
}

GestorEventos.Cliente/Controllers/EventoController.cs
using GestorEventos.Cliente.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json.Serialization;

namespace GestorEventos.Cliente.Controllers
{
    public class EventoController : Controller
    {
        private readonly HttpClient _httpClient;

        public EventoController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:44391/api");
        }
        public async Task<IActionResult> Index()
        {
            var response = await _httpClient.GetAsync("api/Evento");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var eventos = JsonConvert.DeserializeObject<IEnumerable<Eventos>>(content);
                return View("Index", eventos);
            }

            return View(new List<Eventos>());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Eventos evento)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(evento);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Evento", content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al crear el evento, valide los campos.");
                }
            }
            return View(evento);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Evento/id:int?id={id}");
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var evento = JsonConvert.DeserializeObject<Eventos>(content);

                return View(evento);
            }
            else
            {
                return RedirectToAction("Details");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Eventos evento)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(evento);

                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PutAsync($"/api/Evento/{id}", content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index", new { id });
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al actualizar el evento");
                }
            }
            return View(evento);
        }

        public async Task<IActionResult> Details(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Evento/id:int?id={id}");

            if (response.IsSuccessStatusCode) 
            {
                var content = await response.Content.ReadAsStringAsync();
                var evento = JsonConvert.DeserializeObject<Eventos>(content);

                return View(evento);
            }
            else
            {
                return RedirectToAction("Details");
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Evento/{id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Error al eliminar el evento";
                return RedirectToAction("Index");
            }
        }
    }
}

GestorEventos.Cliente/Controllers/HomeController.cs
using GestorEventos.Cliente.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestorEventos.Cliente.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GestorEventos.Cliente/Views/Evento/Create.cshtml
@model GestorEventos.Cliente.Models.Eventos

@{
    ViewData["Title"] = "Create";
}

<div class="card text-primary">
    <div class="card-header text-center">
        <h5>Creacion de Eventos</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8 container">
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="eventName" class="control-label">Nombre del Evento <span style="color:red">*</span></label>
                                        <input asp-for="eventName" class="form-control" />
                                        <span asp-validation-for="eventName" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="eventDescription" class="control-label">Descripcion del Evento <span style="color:red">*</span></label>
                                        <textarea asp-for ="eventDescription" class="form-control"></textarea>
                                        <span asp-validation-for="eventDescription" class="text-danger"></span>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col">
                                            <label asp-for="startDate" class="control-label">Fecha de Inicio</label>
                                            <input type="date" asp-for="startDate" class="form-control" aria-describedby="dateHelp" />
                                            <span asp-validation-for="startDate" class="text-danger"></span>
                                        </div>
                                        <div class="col">
                                            <label asp-for="endDate" class="control-label">Fecha de Culminacion</label>
                                            <input type="date" asp-for="endDate" class="form-control" aria-describedby="dateHelp" />
                                            <span asp-validation-for="endDate" class="text-danger"></span>
                                        </div>
                                        <div class="col">
                                            <label asp-for="eventStatus" class="control-label">Estatus del Evento</label>
                                            <select asp-for="eventStatus" class="form-select" aria-label="Default select example">
                                                <option value="">Seleccione una opcion...</option>
                                                <option value="Confirmado">Confirmado</option>
                                                <option value="Proximamente">Proximamente</option>
                                                <option value="Cancelado">Cancelado</option>
                                            </select>
                                            <span asp-validation-for="eventStatus" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <hr/>
                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-primary float-end" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted text-center">
        Crud Eventos
    </div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestorEventos.Cliente/Views/Evento/Details.cshtml
@model GestorEventos.Cliente.Models.Eventos

@{
    ViewData["Title"] = "Details";
}

<div class="card text-primary">
    <div class="card-header text-center">
        <h5>Detalle del Evento @Html.DisplayFor(model => model.eventName)</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <hr />
                    </div>
                    <div class="panel-body">
                        <table class="table table-hover table-responsive table-striped" id="Eventos" width="50%">
                            <thead>
                                <tr>
                                    <th scope="col">Descripcion del Evento</th>
                                    <th scope="col">Fecha de Inicio</th>
                                    <th scope="col">Fecha de Culminacion</th>
                                    <th scope="col">Estatus</th>
                                </tr>
                            </thead>
                            <tbody class="table-hover">                                
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => model.eventDescription)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.startDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.endDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.eventStatus)
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="panel-footer">
                        <a asp-action="Index" class="btn btn-success float-start">Regresar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted text-center">
        Crud Eventos
    </div>
</div>







@* <h1>Details</h1> *@

@* <div>
    <h4>Eventos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.eventId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.eventId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.eventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.eventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.eventDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.eventDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.startDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.startDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.endDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.endDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.eventStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.eventStatus)
        </dd>
    </dl>
</div>
 *@

GestorEventos.Cliente/Views/Evento/Edit.cshtml
@model GestorEventos.Cliente.Models.Eventos

@{
    ViewData["Title"] = "Edit";
}
<div class="card text-primary">
    <div class="card-header text-center">
        <h5>Edicion de Eventos</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8 container">
                                <form asp-action="Edit">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group visually-hidden">
                                        <label asp-for="eventId" class="control-label"></label>
                                        <input asp-for="eventId" class="form-control" />
                                        <span asp-validation-for="eventId" class="text-danger"></span>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label asp-for="eventName" class="control-label">Nombre del Evento <span style="color:red">*</span></label>
                                        <input asp-for="eventName" class="form-control" />
                                        <span asp-validation-for="eventName" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="eventDescription" class="control-label">Descripcion del Evento <span style="color:red">*</span></label>
                                        <textarea asp-for="eventDescription" class="form-control"></textarea>
                                        <span asp-validation-for="eventDescription" class="text-danger"></span>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col">
                                            <label asp-for="startDate" class="control-label">Fecha de Inicio</label>
                                            <input type="date" asp-for="startDate" class="form-control" aria-describedby="dateHelp" />
                                            <span asp-validation-for="startDate" class="text-danger"></span>
                                        </div>
                                        <div class="col">
                                            <label asp-for="endDate" class="control-label">Fecha de Culminacion</label>
                                            <input type="date" asp-for="endDate" class="form-control" aria-describedby="dateHelp" />
                                            <span asp-validation-for="endDate" class="text-danger"></span>
                                        </div>
                                        <div class="col">
                                            <label asp-for="eventStatus" class="control-label">Estatus del Evento</label>
                                            <select asp-for="eventStatus" class="form-select" aria-label="Default select example">
                                                <option value="">Seleccione una opcion...</option>
                                                <option value="Confirmado">Confirmado</option>
                                                <option value="Proximamente">Proximamente</option>
                                                <option value="Cancelado">Cancelado</option>
                                            </select>
                                            <span asp-validation-for="eventStatus" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="form-group">
                                        <div class="col">
                                            <a asp-action="Index" class="btn btn-success float-start">Regresar</a>
                                            <input type="submit" value="Guardar" class="btn btn-primary float-end" />
                                        </div>
                                        
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted text-center">
        Crud Eventos
    </div>
    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</div>

@* <h1>Edit</h1>

<h4>Eventos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="eventId" class="control-label"></label>
                <input asp-for="eventId" class="form-control" />
                <span asp-validation-for="eventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="eventName" class="control-label"></label>
                <input asp-for="eventName" class="form-control" />
                <span asp-validation-for="eventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="eventDescription" class="control-label"></label>
                <input asp-for="eventDescription" class="form-control" />
                <span asp-validation-for="eventDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="startDate" class="control-label"></label>
                <input asp-for="startDate" class="form-control" />
                <span asp-validation-for="startDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="endDate" class="control-label"></label>
                <input asp-for="endDate" class="form-control" />
                <span asp-validation-for="endDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="eventStatus" class="control-label"></label>
                <input asp-for="eventStatus" class="form-control" />
                <span asp-validation-for="eventStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 *@

GestorEventos.Cliente/Views/Evento/Index.cshtml
@model IEnumerable<GestorEventos.Cliente.Models.Eventos>

<div class="card text-primary">
    <div class="card-header text-center">
        <h5>Listado de Eventos</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a asp-action="Create" class="btn btn-outline-info btn-sm">
                            <img src="~/images/new-icon.png" alt="Nuevo" width="59" height="59">
                        </a>
                        <hr />
                    </div>
                    <div class="panel-body">
                        <table class="table table-hover table-responsive table-striped" id="Eventos" width="50%">
                            <thead>
                                <tr>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Inicio</th>
                                    <th scope="col">Estatus</th>
                                    <th scope="col">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="table-hover">
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.eventName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.startDate)
                                        </td>
                                        <td>
                                            @if (item.eventStatus == "Confirmado")
                                            {
                                                <img src="~/images/confirmed-icon.png" alt="Confirmado" title="Confirmado" width="30" height="30" />
                                            }
                                            @if (item.eventStatus == "Proximamente")
                                            {
                                                <img src="~/images/standby-icon.png" alt = "Proximamente" title = "Proximamente" width = "30" height = "30" />
                                            }
                                            @if (item.eventStatus == "Cancelado")
                                            {
                                                <img src="~/images/cancel-icon.png" alt = "Cancelado" title = "Cancelado" width = "30" height = "30" />
                                            }
                                        </td>

                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.eventId" class="btn btn-outline-warning btn-sm">
                                                <img src="~/images/edit-icon.png" alt="Editar" width="25" height="25">
                                            </a>
                                            <a asp-action="Details" asp-route-id="@item.eventId" class="btn btn-outline-info btn-sm">
                                                <img src="~/images/details-icon.png" alt="Detalle" width="25" height="25">
                                            </a>
                                            <a asp-action="Delete" asp-route-id="@item.eventId" class="btn btn-outline-danger btn-sm">
                                                <img src="~/images/delete-icon.png" alt="Eliminar" width="25" height="25">
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted text-center">
        Crud Eventos
    </div>
</div>

GestorEventos.Cliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GestorEventos.Cliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/images/logo.ico">
    <title>@ViewData["Title"] Gestor de Eventos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorEventos.Cliente.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Evento" asp-action="Index">
                    Gestor de Eventos
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a> *@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gestor de Eventos - <a asp-area="" asp-controller="Evento" asp-action="Index">Listado</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>